# Generated by Django 4.1.3 on 2022-11-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_path', models.CharField(max_length=500)),
                ('job', models.CharField(max_length=40)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(max_length=50)),
                ('hiring_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees_Informations',
            },
        ),
    ]
