# Generated by Django 4.1.3 on 2022-11-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformation',
            name='photo_path',
            field=models.ImageField(blank='', default='', upload_to='img'),
        ),
    ]
